### ISSUE TITLE
css idea

### ISSUE THREAD

**Issue by Tjoosten** [bcit-ci/codeigniter-website#26]
Maybe we can add LESS of SCSS files to this project.

**Comment by jim-parry** [comment]
Given the simplicity of the site, is there enough payback to introducing such a technique?
Would it play nicely with travis-ci?

@michalsn Thoughts?

**Comment by michalsn** [comment]
As far as I remember there was a LESS version (not in repo), but since then there were some changes in design introduced only to CSS version. But I can handle it - it's not a big problem.

Unfortunately I'm not familiar with Travis, so I can't tell if there is some simple solution to compile LESS on every build. From the other hand... if we introduce LESS files, we can require from users to build files before sending them to repo.

Having LESS version could be very beneficial. Especially if someone is thinking about big changes on website. But for now I don't see any interest on that matter in community, so... I'm not sure is it worth it :)

**Comment by Tjoosten** [comment]
I think it is worth it

**Comment by jim-parry** [comment]
Not seeing any traction on this.
